In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Investigating the 2016-17 transactions dataset

In [3]:
df_transactions = pd.read_csv("data/transactions_2016_2017.csv", low_memory=False)

In [4]:
df_transactions.head()

,cust_id,order_date,pack_date,sale_id,sale_discount_applied,sale_revenue,returned_to_shop_id,prod_id,prod_size,prod_web_only,...,prod_type_4,prod_type_5,prod_heel,prod_material,prod_insole,prod_print,prod_comfort_sole,prod_comfort_wear,prod_clasp,prod_outlet
0,klantwj2374mzmab,2016-01-01,2016-01-04,wa46phiwo6neterg,-35.70,83.30,NaN,543rj4mzzjnzkbil,30,0,...,NaN,boots (velcro),NaN,leather,1.0,NaN,NaN,NaN,velcro,0
1,klantwj2374mzmab,2016-01-01,2016-01-04,wa46phiwo6neterg,-39.98,0.00,ztodvuuaje,7ewnqhtrquent4cy,44,0,...,NaN,dress boots,NaN,leather,0.0,NaN,NaN,NaN,zipper,0
2,a63atwr2ig2jfprr,2016-01-01,2016-01-04,p4y4726y24dcxawf,-24.00,0.00,5tiaacoboa,cwtye5jwqr43a56i,38.5,0,...,high-top sneakers,lace-up shoes,NaN,suede,NaN,NaN,NaN,NaN,NaN,0
3,zr7ihbfbi6gcy2tz,2016-01-01,2016-01-05,3etkl2xv6pxku4kt,-26.23,43.72,NaN,mqw2seipp2wtylnw,35,0,...,NaN,velcro shoes,NaN,synthetic leather,0.0,NaN,NaN,breathable,velcro,0
4,dt7cthjqnjmkbiu6,2016-01-01,2016-01-05,lneitdgyfvrie3jo,-29.98,0.00,geja5b25na,5ut47kvr6zlx6y62,25,0,...,NaN,boots (velcro),NaN,NaN,NaN,NaN,NaN,NaN,velcro,0

In [5]:
df_transactions.columns

Index(['cust_id', 'order_date', 'pack_date', 'sale_id',
       'sale_discount_applied', 'sale_revenue', 'returned_to_shop_id',
       'prod_id', 'prod_size', 'prod_web_only', 'prod_season', 'prod_brand',
       'prod_title', 'prod_color', 'prod_type_1', 'prod_type_3', 'prod_type_4',
       'prod_type_5', 'prod_heel', 'prod_material', 'prod_insole',
       'prod_print', 'prod_comfort_sole', 'prod_comfort_wear', 'prod_clasp',
       'prod_outlet'],
      dtype='str')

In [6]:
df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 344212 entries, 0 to 344211
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   cust_id                344212 non-null  str
 1   order_date             344212 non-null  str
 2   pack_date              344212 non-null  str
 3   sale_id                344212 non-null  str
 4   sale_discount_applied  344212 non-null  float64
 5   sale_revenue           344212 non-null  float64
 6   returned_to_shop_id    63930 non-null   str
 7   prod_id                344212 non-null  str
 8   prod_size              344212 non-null  str
 9   prod_web_only          344212 non-null  int64
 10  prod_season            344212 non-null  str
 11  prod_brand             344212 non-null  str
 12  prod_title             344212 non-null  str
 13  prod_color             344212 non-null  str
 14  prod_type_1            344212 non-null  str
 15  prod_type_3            344212 non-null  str
 16  prod_type_4            142459 non-null  str
 17  prod_type_5            337952 non-null  str
 18  prod_heel              212011 non-null  str
 19  prod_material          321471 non-null  str
 20  prod_insole            318247 non-null  float64
 21  prod_print             77470 non-null   str
 22  prod_comfort_sole      42139 non-null   str
 23  prod_comfort_wear      32521 non-null   str
 24  prod_clasp             305557 non-null  str
 25  prod_outlet            344212 non-null  int64
dtypes: float64(3), int64(2), str(21)
memory usage: 68.3 MB

In [7]:
df_transactions.shape

(344212, 26)

### Converting the  data type of columns

### Fixing Date columns

In [8]:
df_transactions.loc[:, df_transactions.columns.str.contains("date", case=False)]

        order_date   pack_date
0       2016-01-01  2016-01-04
1       2016-01-01  2016-01-04
2       2016-01-01  2016-01-04
3       2016-01-01  2016-01-05
4       2016-01-01  2016-01-05
...            ...         ...
344207  2017-12-31  2018-01-02
344208  2017-12-31  2018-01-02
344209  2017-12-31  2018-01-02
344210  2017-12-31  2018-01-02
344211  2017-12-31  2018-01-02

[344212 rows x 2 columns]

In [9]:
df_transactions.loc[:, df_transactions.columns.str.contains("date", case=False)].dtypes

order_date    str
pack_date     str
dtype: object

In [10]:
cols_to_convert = df_transactions.columns[
    df_transactions.columns.str.contains("date", case=False)
]

In [11]:
df_transactions[cols_to_convert] = df_transactions[cols_to_convert].apply(
    pd.to_datetime, errors="coerce", format="%Y-%m-%d"
)

In [12]:
df_transactions.head()

,cust_id,order_date,pack_date,sale_id,sale_discount_applied,sale_revenue,returned_to_shop_id,prod_id,prod_size,prod_web_only,...,prod_type_4,prod_type_5,prod_heel,prod_material,prod_insole,prod_print,prod_comfort_sole,prod_comfort_wear,prod_clasp,prod_outlet
0,klantwj2374mzmab,2016-01-01,2016-01-04,wa46phiwo6neterg,-35.70,83.30,NaN,543rj4mzzjnzkbil,30,0,...,NaN,boots (velcro),NaN,leather,1.0,NaN,NaN,NaN,velcro,0
1,klantwj2374mzmab,2016-01-01,2016-01-04,wa46phiwo6neterg,-39.98,0.00,ztodvuuaje,7ewnqhtrquent4cy,44,0,...,NaN,dress boots,NaN,leather,0.0,NaN,NaN,NaN,zipper,0
2,a63atwr2ig2jfprr,2016-01-01,2016-01-04,p4y4726y24dcxawf,-24.00,0.00,5tiaacoboa,cwtye5jwqr43a56i,38.5,0,...,high-top sneakers,lace-up shoes,NaN,suede,NaN,NaN,NaN,NaN,NaN,0
3,zr7ihbfbi6gcy2tz,2016-01-01,2016-01-05,3etkl2xv6pxku4kt,-26.23,43.72,NaN,mqw2seipp2wtylnw,35,0,...,NaN,velcro shoes,NaN,synthetic leather,0.0,NaN,NaN,breathable,velcro,0
4,dt7cthjqnjmkbiu6,2016-01-01,2016-01-05,lneitdgyfvrie3jo,-29.98,0.00,geja5b25na,5ut47kvr6zlx6y62,25,0,...,NaN,boots (velcro),NaN,NaN,NaN,NaN,NaN,NaN,velcro,0

In [13]:
df_transactions.dtypes

cust_id                             str
order_date               datetime64[us]
pack_date                datetime64[us]
sale_id                             str
sale_discount_applied           float64
sale_revenue                    float64
returned_to_shop_id                 str
prod_id                             str
prod_size                           str
prod_web_only                     int64
prod_season                         str
prod_brand                          str
prod_title                          str
prod_color                          str
prod_type_1                         str
prod_type_3                         str
prod_type_4                         str
prod_type_5                         str
prod_heel                           str
prod_material                       str
prod_insole                     float64
prod_print                          str
prod_comfort_sole                   str
prod_comfort_wear                   str
prod_clasp                          str
prod_outlet                       int64
dtype: object

In [14]:
df_transactions[cols_to_convert].isna().sum()

order_date    0
pack_date     0
dtype: int64

all the date columns are turned to appropriate datetime objects. the formats were consistent, so there are no null values

### Fixing `prod_size`

In [15]:
df_transactions["prod_size"].sample(n=10)

85135     38
9742      38
297272    41
276051    47
207710    35
206592    42
189103    42
99167     25
128754    38
145874    41
Name: prod_size, dtype: str

In [16]:
pd.to_numeric(df_transactions["prod_size"], errors="coerce").isna().sum()

np.int64(1)

there seems to be a value in the `prod_size` which is not numeric

In [17]:
not_numeric_mask = pd.to_numeric(df_transactions["prod_size"], errors="coerce").isna()

In [18]:
df_transactions.loc[not_numeric_mask, "prod_size"]

336680    XS
Name: prod_size, dtype: str

XS is not a valid shoe size, and since it's only one record we can safely drop it

In [19]:
df_transactions = df_transactions[~not_numeric_mask]

In [20]:
df_transactions.shape

(344211, 26)

In [21]:
df_transactions["prod_size"] = pd.to_numeric(df_transactions["prod_size"])

In [22]:
df_transactions["prod_size"].dtype

dtype('float64')

## exploring categorical text columns

In [23]:
df_transactions["prod_type_1"].value_counts()

prod_type_1
women    186636
boys      55827
men       54180
girls     47568
Name: count, dtype: int64

In [24]:
df_transactions["prod_season"].sample(n=5)

340976     Z18
160257     Z17
284174    SZ17
217378     W16
11225      W15
Name: prod_season, dtype: str

In [25]:
len(df_transactions["prod_season"].unique())

23

In [26]:
len(df_transactions["prod_season"].str.lower().str.strip().unique())

23

In [27]:
df_transactions["prod_brand"].head()

0    STONES and BONES
1         Mario Rossi
2               Gabor
3                Geox
4    STONES and BONES
Name: prod_brand, dtype: str

In [28]:
len(df_transactions["prod_brand"].unique())

493

In [29]:
len(df_transactions["prod_brand"].str.lower().str.strip().unique())

493

In [30]:
df_transactions["prod_title"].head()

0       Bruine Velcrobottine STONES and BONES
1                     Mario Rossi Cognac Boot
2    Gabor Blauwe Veterschoen met Dierenprint
3                    Geox Blauwe Velcroschoen
4          STONES and BONES Taupe Velcroboots
Name: prod_title, dtype: str

In [31]:
len(df_transactions["prod_title"].unique())

21301

In [32]:
len(df_transactions["prod_title"].str.lower().str.strip().unique())

21268

there seems to be something going on here. use the fixed one in the data frame

In [33]:
df_transactions["prod_title"] = df_transactions["prod_title"].str.lower().str.strip()

In [34]:
df_transactions["prod_color"].head()

0    dark brown
1        cognac
2          blue
3     dark blue
4         taupe
Name: prod_color, dtype: str

In [35]:
len(df_transactions["prod_color"].unique())

41

In [36]:
len(df_transactions["prod_color"].str.lower().str.strip().unique())

41

In [37]:
df_transactions["prod_type_1"].value_counts()

prod_type_1
women    186636
boys      55827
men       54180
girls     47568
Name: count, dtype: int64

In [38]:
df_transactions["prod_type_3"].value_counts()

prod_type_3
sneakers                             68773
sandals                              46074
low shoes                            41717
high shoes                           31271
ankle boots                          30084
pumps                                29304
boots                                21205
flip-flops                           18898
slippers                             15064
ballet flats                         10167
low shoes, sneakers                   9086
sneakers, sports shoes                7232
dress shoes                           6566
snow boots                            1730
high shoes, sneakers                  1726
baby shoes                             925
ankle boots, boots                     917
sports shoes                           692
ankle boots, sneakers                  639
high shoes, boots                      405
dress shoes, low shoes                 246
low shoes, pumps                       240
high shoes, low shoes                  199
boots, snow boots                      180
low shoes, sneakers, sports shoes      122
slippers, flip-flops                   109
ankle boots, pumps                     104
high shoes, low shoes, sneakers         93
dress shoes, high shoes                 90
low shoes, sandals                      73
high shoes, hiking shoes                68
ankle boots, low shoes                  52
sandals, flip-flops                     34
low shoes, flip-flops                   31
pumps, sandals                          30
low shoes, sports shoes                 26
hiking shoes                            12
high shoes, snow boots                  11
ankle boots, snow boots                  7
ballet flats, low shoes                  5
boots, ankle boots                       4
Name: count, dtype: int64

**NOTE:** Some of them have multiple, overlapping categories. should we do something with it?

In [39]:
df_transactions["prod_type_4"].isna().sum()

np.int64(201752)

In [40]:
df_transactions["prod_type_5"].value_counts()

prod_type_5
low-top sneakers          46988
lace-up shoes             23862
lace-up boots             22338
dress sandals             21009
ankle boots               18402
high-top sneakers         14114
slippers                  14025
classic pumps             13957
sport sandals             12060
casual shoes              10469
slides                    10014
boots                      9466
slip-on shoes              8973
flip-flops                 8701
baby shoes                 8681
dress boots                7528
running sneakers           7394
chunky boots               6791
classic ballet flats       6473
wedge sandals              6392
high-heel pumps            5839
velcro shoes               5582
slip-on sneakers           4533
boots (velcro)             4299
strap pumps                4016
strap ballet flats         3841
rain boots                 3176
boat shoes                 2659
platform pumps             2345
wedge sneakers             2269
sports shoes               2125
water sandals              1957
wedge pumps                1913
snow boots                 1771
baby sandals               1769
high-heel sandals          1756
baby slippers              1621
zipper & lace-up shoes     1502
espadrilles                1405
platform sandals           1214
over-the-knee boots         910
moccasins                   863
open-heel pumps             658
baby boots                  581
peep-toe pumps              562
light-up shoes              263
baby sneakers               213
wide-calf boots             210
mules                       181
loafers                     160
narrow-calf boots           121
Name: count, dtype: int64

In [41]:
df_transactions["prod_type_5"].isna().sum()

np.int64(6260)

In [42]:
# NOTE: maybe categorize this one??
df_transactions["prod_heel"].value_counts()

prod_heel
<2.5 cm     136843
5-8 cm       35712
2.5-5 cm     32957
>8 cm         6499
Name: count, dtype: int64

In [43]:
df_transactions["prod_heel"].isna().sum()

np.int64(132200)

In [44]:
df_transactions["prod_material"].value_counts()

prod_material
leather                                       142502
textile                                        60928
synthetic leather                              42304
suede                                          29895
nubuck                                         14049
patent leather, leather                         8900
synthetic                                       6767
synthetic leather, patent leather               4777
rubber                                          2104
leather, textile                                1368
synthetic leather, textile                      1184
suede, textile                                  1154
wool                                            1088
synthetic leather, leather                       873
suede, patent leather                            651
velour                                           477
synthetic wool, nubuck                           402
suede, leather                                   320
suede, synthetic leather                         196
patent leather, nubuck                           169
patent leather                                   138
patent leather, textile                          136
synthetic, patent leather                        117
synthetic, textile                               113
nubuck, textile                                  110
suede, synthetic wool                            102
synthetic leather, patent leather, leather        97
synthetic leather, patent leather, textile        52
leather, nubuck                                   45
suede, leather, textile                           43
leather, rubber                                   35
synthetic leather, synthetic wool                 33
suede, wool                                       32
synthetic leather, nubuck                         31
synthetic leather, velour                         31
synthetic leather, synthetic                      30
synthetic leather, synthetic, textile             24
synthetic wool, leather                           20
suede, synthetic leather, patent leather          19
synthetic, leather                                19
synthetic leather, leather, textile               18
synthetic wool, nubuck, textile                   15
synthetic leather, patent leather, velour         12
suede, synthetic leather, textile                 10
suede, patent leather, leather                    10
synthetic leather, textile, velour                10
leather, nubuck, textile                           9
suede, nubuck                                      8
synthetic wool, textile                            7
patent leather, leather, velour                    6
nubuck, textile, velour                            6
synthetic leather, nubuck, textile                 5
suede, synthetic leather, leather, textile         5
suede, velour                                      4
patent leather, leather, textile                   3
textile, velour                                    3
synthetic wool, velour                             3
patent leather, velour                             1
Name: count, dtype: int64

In [45]:
len(df_transactions["prod_material"].unique())

59

In [46]:
len(df_transactions["prod_material"].str.lower().str.strip().unique())

59

In [47]:
# NOTE: maybe turn this into numeric, but there are null values
df_transactions["prod_insole"].value_counts()

prod_insole
0.0    230583
1.0     87663
Name: count, dtype: int64

In [48]:
df_transactions["prod_insole"].unique()

array([ 1.,  0., nan])

In [49]:
df_transactions["prod_insole"] = df_transactions["prod_insole"].astype("float64")

In [50]:
df_transactions["prod_print"].value_counts()

prod_print
metallic                         25029
glitter                          13983
snake print                       7733
bows                              3628
floral                            3413
                                 ...
hearts, metallic, sequins            2
houndstooth                          1
floral, metallic, polka dots         1
glitter, rhinestones                 1
perforated, glitter, metallic        1
Name: count, Length: 128, dtype: int64

In [51]:
len(df_transactions["prod_print"].unique())

129

In [52]:
len(df_transactions["prod_print"].str.lower().str.strip().unique())

129

In [53]:
len(df_transactions["prod_comfort_sole"].unique())

52

In [54]:
len(df_transactions["prod_comfort_sole"].unique())

52

In [55]:
df_transactions["prod_comfort_wear"].value_counts()

prod_comfort_wear
breathable                                    15954
water-repellent                                6576
easy closure                                   3805
warm lining                                    3206
warm lining, water-repellent                   1251
breathable, easy closure                        829
breathable, water-repellent                     645
breathable, warm lining, water-repellent        123
breathable, warm lining                          81
easy closure, water-repellent                    21
easy closure, warm lining                        12
easy closure, warm lining, water-repellent       12
breathable, easy closure, warm lining             6
Name: count, dtype: int64

In [56]:
df_transactions["prod_clasp"].value_counts()

prod_clasp
laces                                      87516
slip-on                                    58429
velcro                                     40312
zipper                                     35499
buckle                                     28268
zipper, zipper and laces, laces            15444
zipper, laces                              14533
elastic                                     7618
strap, buckle                               3696
strap, velcro                               3488
elastic, velcro                             2854
elastic, zipper                             1170
velcro, laces                               1087
strap                                        887
drawstring                                   696
zipper and laces                             508
zipper and laces, laces                      479
strap, elastic                               370
elastic, laces                               341
snap button                                  293
elastic, zipper, zipper and laces            280
strap, slip-on                               232
buckle, slip-on                              207
buckle, zipper                               130
snap button, zipper                          128
elastic, slip-on                             128
zipper, zipper and laces                     112
zipper, zipper and laces, velcro, laces      111
strap, laces                                 103
zipper, velcro                                79
buckle, zipper, zipper and laces, laces       74
strap, zipper                                 68
strap, snap button                            64
drawstring, zipper                            59
strap, elastic, velcro                        55
strap, zipper, laces                          46
strap, drawstring                             44
buckle, velcro                                31
slip-on, zipper                               28
click lock                                    18
strap, slip-on, drawstring                    15
elastic, slip-on, velcro                      15
slip-on, laces                                14
elastic, buckle                               10
buckle, zipper, laces                          6
strap, elastic, zipper                         5
snap button, elastic                           4
slip-on, velcro                                2
Name: count, dtype: int64

In [57]:
df_transactions["prod_outlet"].value_counts()

prod_outlet
0    343838
1       373
Name: count, dtype: int64

### Creating a new feature based on `returned_to_shop_id`

In [58]:
df_transactions["returned_to_shop_id"].isna().sum()  # these were not returned

np.int64(280281)

In [59]:
df_transactions["is_returned"] = np.where(
    df_transactions["returned_to_shop_id"].notna(), 1, 0
)

In [60]:
df_transactions["is_returned"].value_counts()

is_returned
0    280281
1     63930
Name: count, dtype: int64

## Looking for duplicates

In [61]:
df_transactions.duplicated().sum()

np.int64(1063)

In [62]:
df_transactions.drop_duplicates(inplace=True)

In [63]:
df_transactions.shape

(343148, 27)

# Creating train and valid datasets

In [64]:
df_revenues = pd.read_csv("data/customer_clv_train.csv")

In [65]:
df_revenues.head()

            cust_id  revenue_2018_2019
0  klantwj2374mzmab             209.85
1  a63atwr2ig2jfprr              82.93
2  zr7ihbfbi6gcy2tz              89.95
3  dt7cthjqnjmkbiu6               0.00
4  etcrrgcbrzfovyzj               0.00

In [66]:
df_revenues_train, df_revenues_valid = train_test_split(df_revenues, test_size=0.2, random_state=7)

In [67]:
df_revenues_train

                 cust_id  revenue_2018_2019
30982   7gnxbv6qflrjaf4y             398.65
3671    lapyzcy7ih35kmyp               0.00
86885   gl65ix4vdajwgt4q               0.00
92114   v74tsfuqcldr2rqo               0.00
106058  u6qowqu3fibkflon               0.00
...                  ...                ...
104003  ysljla6vmzmblfcr              78.00
10742   3edrxpr3slpkayqz               0.00
49689   pb2szqg4faifdk2q               0.00
58564   qfjnl3nto35u7x4n               0.00
61615   oprcuf34ibronf5q               0.00

[93272 rows x 2 columns]

In [68]:
df_revenues_train.to_csv("data/train_targets.csv", index=False)

In [69]:
df_revenues_valid

                cust_id  revenue_2018_2019
84568  xmc3wbm46yz2dxn7               0.00
63136  rksab34x4wteafvi             384.10
28882  var67cdxemwxikbu               0.00
63730  htpwcpsafpqhrpeo             269.00
24994  bskg2cyzqwizlt72               0.00
...                 ...                ...
2853   dwkeotzzjc22re5d               0.00
24532  cotjjxodulqh42pz              71.95
13081  h3pep4e4qvzntbfh               0.00
66292  yp7ecqe7szg3j65w             149.09
62318  rxret45ojycptx2g               0.00

[23319 rows x 2 columns]

In [70]:
df_revenues_valid.to_csv("data/valid_targets.csv", index=False)

In [71]:
train_cust_ids = df_revenues_train["cust_id"]

In [72]:
valid_cust_ids = df_revenues_valid["cust_id"]

In [73]:
df_train = df_transactions[df_transactions["cust_id"].isin(train_cust_ids)].copy()

In [74]:
df_valid = df_transactions[df_transactions["cust_id"].isin(valid_cust_ids)].copy()

In [75]:
df_train.shape

(219128, 27)

In [76]:
df_valid.shape

(55183, 27)

In [77]:
df_train.to_csv("data/train_clean.csv", index=False)

In [78]:
df_valid.to_csv("data/valid_clean.csv", index=False)

In [79]:
df_train["order_date"]

0        2016-01-01
1        2016-01-01
2        2016-01-01
3        2016-01-01
4        2016-01-01
            ...
344206   2017-12-31
344207   2017-12-31
344208   2017-12-31
344209   2017-12-31
344211   2017-12-31
Name: order_date, Length: 219128, dtype: datetime64[us]